version: '3.1'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  apiserver:
    build:
      context: ./ApiServer
    depends_on: 
      - mongo
  webapp:
    build: 
      context: ./WebApp
    depends_on: 
      - apiserver
    ports: 
      - 3000:3000