version: '3.1'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  apiserver:
    build:
      context: ./ApiServer
    depends_on: 
      - mongo
    ports:
      - "3001:3001"
    links:
      - mongo
  webapp:
    build: 
      context: ./WebApp
    depends_on: 
      - apiserver
    ports:
      - "3000:3000"
    links:
      - apiserver